auto sync with Isabelle2003

diff --git a/admin/publish b/admin/publish
--- a/admin/publish
+++ b/admin/publish
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# $Id: publish,v 1.3 2004-03-19 21:07:38 lsf37 Exp $
+# $Id: publish,v 1.4 2004-03-23 15:07:05 lsf37 Exp $
 # Author: Gerwin Klein, NICTA
 # License: GPL (GNU GENERAL PUBLIC LICENSE)
 #
@@ -102,7 +102,7 @@ EXPORT=$EXPORT_PRE-$DATE
 
 echo "Exporting from CVS"
 [ -e "afp-export-$DATE" ] && fail "Export directory [afp-export-$DATE] exists. Please remove before running this script."
-$CVS -q -d $REPOS export -P -r $TAG -d afp-export-$DATE thys web || fail "CVS export failed."
+$CVS -q -d $REPOS export -r $TAG -d afp-export-$DATE thys web || fail "CVS export failed."
 cd afp-export-$DATE
 mv thys $EXPORT
 
