auto sync with Isabelle2003

diff --git a/admin/publish b/admin/publish
--- a/admin/publish
+++ b/admin/publish
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# $Id: publish,v 1.2 2004-02-25 06:22:34 lsf37 Exp $
+# $Id: publish,v 1.3 2004-03-19 21:07:38 lsf37 Exp $
 # Author: Gerwin Klein, NICTA
 # License: GPL (GNU GENERAL PUBLIC LICENSE)
 #
@@ -38,7 +38,7 @@ function usage()
   echo "Options:"
   echo "  -f             do not ask before publishing"
   echo "  -t <isatool>   use specified path to isatool"
-  echo "  -r             use env variable ISABELLE_RELEASE to find isatool"
+  echo "  -r             use env variable ISABELLE_RELEASES to find isatool"
   echo
   echo "Examples:"
   echo "  $PRG -t /usr/proj/Isabelle2003/bin/isatool Isabelle2003 Example-Submission"  
@@ -72,9 +72,8 @@ while getopts "t:rf" OPT
 do
     case "$OPT" in
       r)
-        [ "$ISABELLE_RELEASE" == "" ] && fail "ISABELLE_RELEASE not set"
-        ISATOOL="$ISABELLE_RELEASE/bin/isatool"
-        check_isatool
+        [ "$ISABELLE_RELEASES" == "" ] && fail "ISABELLE_RELEASES not set"
+        USE_RELEASE=1
         ;;
       f)
         INTERACTIVE="no"
@@ -91,13 +90,19 @@ shift $(($OPTIND - 1))
 TAG="$1" 
 shift
 
+if [ "$USE_RELEASE" == "1" ]; then
+    ISATOOL="$ISABELLE_RELEASES/$TAG/bin/isatool"
+    check_isatool
+fi
+
+
 EXPORT=$EXPORT_PRE-$DATE
 
 ###
 
 echo "Exporting from CVS"
 [ -e "afp-export-$DATE" ] && fail "Export directory [afp-export-$DATE] exists. Please remove before running this script."
-$CVS -q -d $REPOS export -r $TAG -d afp-export-$DATE thys web || fail "CVS export failed."
+$CVS -q -d $REPOS export -P -r $TAG -d afp-export-$DATE thys web || fail "CVS export failed."
 cd afp-export-$DATE
 mv thys $EXPORT
 
diff --git a/admin/regression b/admin/regression
--- a/admin/regression
+++ b/admin/regression
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# $Id: regression,v 1.5 2004-03-14 21:08:31 lsf37 Exp $
+# $Id: regression,v 1.6 2004-03-19 21:07:38 lsf37 Exp $
 # Author: Gerwin Klein, NICTA
 # License: GPL (GNU GENERAL PUBLIC LICENSE)
 #
@@ -72,6 +72,7 @@ if [ "$1" == "-" ]; then
   ML_IDENTIFIER=`$ISATOOL getenv -b ML_IDENTIFIER` || fail "could not identify ML system"
   export ISABELLE_IMAGE_PATH="$HOME/isabelle-$SHORT/heaps/$ML_IDENTIFIER/"
   LOG=$LOG-devel-$DATE.log
+  SNAPSHOT=1;
   REPORT=$REPORT-devel
 else
   TAG="-r $1"
@@ -91,7 +92,7 @@ echo "begin cvs update" >> $LOG
 
 # cvs update to newest version of archive 
 cd $WORKING_COPY || fail "could not cd to $WORKING_COPY"
-cvs -q up -d $TAG >> $LOG 2>&1 || fail "could not CVS update."
+cvs -q up -P -d $TAG >> $LOG 2>&1 || fail "could not CVS update."
 
 echo "end cvs update" >> $LOG
 echo >> $LOG
@@ -161,5 +162,21 @@ else
   echo "`date`, $AFP_VER: All tests successful. Elapsed time: $ELAPSED" >> $MASTERLOG
 fi
 
-# clean up
+# clean up tmp
 rm -f $TMP
+
+# make devel snapshot
+if [ "$SNAPSHOT" == "1" ]; then
+    EXPORT=afp-devel
+    STATUS=entry-status.txt
+    WEB=~/html-data/afp/
+    cp $REPORT $WEB/$STATUS
+    cvs -Q export -P -D now -d $EXPORT thys
+    cp $REPORT $EXPORT/$STATUS
+    echo >> $EXPORT/$STATUS
+    echo `date` >> $EXPORT/$STATUS
+    tar cf $EXPORT.tar $EXPORT
+    gzip --best -f $EXPORT.tar
+    mv $EXPORT.tar.gz $WEB
+    rm -rf $EXPORT
+fi
