use afp_build for publishing new entries

diff --git a/admin/publish b/admin/publish
--- a/admin/publish
+++ b/admin/publish
@@ -140,18 +140,16 @@ if [ "$1" != "-" ]; then
     ln -s $EXPORT.tar.gz $TARS/$EXPORT_PRE-current.tar.gz
 
     cd $EXPORT
-    for DIR in $@; do
-        if [ -d $DIR ]; then
-            echo "Generating HTML for [$DIR]"
-            cd $DIR
-            $ISABELLE_TOOL make clean all || fail "isabelle make all failed on [$DIR]"
-            cd ..
-            echo "Tarring [$DIR]"
-            $TAR -cf $EXPORT_PRE-$DIR-$DATE.tar $DIR
-            gzip --best -f $EXPORT_PRE-$DIR-$DATE.tar
-            mv $EXPORT_PRE-$DIR-$DATE.tar.gz ../$TARS
-            ln -s $EXPORT_PRE-$DIR-$DATE.tar.gz ../$TARS/$EXPORT_PRE-$DIR-current.tar.gz
-            echo "Finished [$DIR]"
+    for ENTRY in $@; do
+        if [ -d $ENTRY ]; then
+            echo "Generating HTML for [$ENTRY]"
+            $ISABELLE_TOOL afp_build $ENTRY || fail "isabelle make all failed on [$ENTRY]"
+            echo "Tarring [$ENTRY]"
+            $TAR -cf $EXPORT_PRE-$ENTRY-$DATE.tar $ENTRY
+            gzip --best -f $EXPORT_PRE-$ENTRY-$DATE.tar
+            mv $EXPORT_PRE-$ENTRY-$DATE.tar.gz ../$TARS
+            ln -s $EXPORT_PRE-$ENTRY-$DATE.tar.gz ../$TARS/$EXPORT_PRE-$ENTRY-current.tar.gz
+            echo "Finished [$ENTRY]"
         fi
     done
     cd ..
