manual sync and conflict resolution

diff --git a/admin/publish b/admin/publish
--- a/admin/publish
+++ b/admin/publish
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# $Id: publish,v 1.12 2008-10-05 11:35:27 lsf37 Exp $
+# $Id: publish,v 1.13 2008-11-13 22:17:33 lsf37 Exp $
 # Author: Gerwin Klein, NICTA
 #
 # publishes archive entry + main web pages on SF
@@ -113,7 +113,7 @@ mv thys $EXPORT
 
 if [ "$1" != "-" ]; then
     echo "Cleaning up browser_info directory"
-    BROWSER_INFO=`isabelle getenv -b ISABELLE_BROWSER_INFO` || fail "could not find browser info"
+    BROWSER_INFO=`$ISABELLE_TOOL getenv -b ISABELLE_BROWSER_INFO` || fail "could not find browser info"
     [ -e "$BROWSER_INFO" ] && rm -rf $BROWSER_INFO
 
     HTML_THYS=web/browser_info/$TAG
