refer to correct isatool

diff --git a/admin/regression b/admin/regression
--- a/admin/regression
+++ b/admin/regression
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# $Id: regression,v 1.19 2007-09-01 04:35:06 lsf37 Exp $
+# $Id: regression,v 1.20 2007-09-02 06:44:41 lsf37 Exp $
 # Author: Gerwin Klein, NICTA
 #
 # Automated regression test to be run from cron.
@@ -80,7 +80,7 @@ if [ "$1" == "-" ]; then
   SNAPSHOT=1;
   REPORT=$REPORT-devel
 
-  BROWSER_INFO=`isatool getenv -b ISABELLE_BROWSER_INFO` || fail "could not find browser info"
+  BROWSER_INFO=`$ISATOOL getenv -b ISABELLE_BROWSER_INFO` || fail "could not find browser info"
   [ -e "$BROWSER_INFO" ] && rm -rf $BROWSER_INFO
 
 else
